# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37b34864e6cf8bfbe22305fcf12edb61c246dede7142e03a3998ed95885c7a89b56adbe26abef94c76b01b98561e3b222b20aaa2ddb3ab1ea32c8833b5bd533

test:
  secret_key_base: 92d88b2beecaad711396875d581a2ec6e7eacdc5d99d8a2a7fa7b6c4a381d2084295cd6bd1afe9ffad40784a2535837d0c4f8213bb55d93cd19c37dbfe00cff5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
